"""
Validation Node - Validate the conjectural requirement specification.

This node evaluates the conjectural requirements generated by the Specification
node, scoring each one from 1 to 10 based on quality criteria.
"""

import json
from typing import Optional

from langchain_core.runnables.config import RunnableConfig
from langchain_core.messages import AIMessage, HumanMessage, ToolMessage
from langchain_core.tools import tool
from app.agent.llm_config import get_model, extract_text, DEFAULT_GEMINI_MODEL, DEFAULT_AZURE_OPENAI_JUDGE_MODEL
from langgraph.types import Command, interrupt
from copilotkit.langgraph import copilotkit_customize_config, copilotkit_emit_state, copilotkit_emit_message

from app.agent.state import WorkflowState
from app.agent.models.data_context import DataContext, Evaluation
from app.agent.utils.context_utils import extract_copilotkit_context
from app.agent.prompts.factory import get_prompt
from app.agent.prompts.e01_validation_system_prompt import VALIDATION_SYSTEM_PROMPT
from app.services.conjectural_persistence import persist_conjectural_data
from app.logging_config import get_logger

logger = get_logger(__name__)


@tool
def show_requirements(requirement_ids: str):
    """Tool function to show requirements on the frontend board."""
    return {"success": True}


async def _task_evaluate(
    state: WorkflowState,
    config: RunnableConfig,
    data_context: DataContext,
    model_provider: str,
) -> dict:
    """Task: Evaluate conjectural requirements (human + LLM-as-Judge)."""
    messages = state.get("messages", [])

    context = extract_copilotkit_context(state)
    require_evaluation = context['require_evaluation']

    # --- Step 1: Human evaluation (interrupt) ---
    if require_evaluation:
        requirements_list = []
        for i, cd in enumerate(data_context.conjectural_data):
            if not cd.conjectural_requirements:
                continue
            cr = cd.conjectural_requirements[-1]
            requirements_list.append({
                "requirement_number": i + 1,
                "attempt": cr.attempt,
                "desired_behavior": cr.ferc.desired_behavior,
                "business_need": cr.ferc.business_need,
                "uncertainty": cr.ferc.uncertainty,
                "solution_assumption": cr.qess.solution_assumption,
                "uncertainty_evaluated": cr.qess.uncertainty_evaluated,
                "observation_analysis": cr.qess.observation_analysis,
            })

        logger.info("Sending %s requirements for human evaluation via interrupt", len(requirements_list), extra={"node": "validation"})
        human_evaluation_response = interrupt({
            "type": "hitl_req_approve",
            "requirements": requirements_list,
        })

        interrupt_message = f"✅ User evaluations for **attempt {state['spec_attempt']}** received successfully. Please wait while it is processed."
        messages = messages + [AIMessage(content=interrupt_message)]
        await copilotkit_emit_message(config, interrupt_message)

        try:
            eval_data = json.loads(human_evaluation_response) if isinstance(human_evaluation_response, str) else human_evaluation_response
            evaluations = eval_data.get("evaluations", {})
            logger.info("Human evaluation received for %s requirements", len(evaluations), extra={"node": "validation"})

            for req_number_str, evaluation in evaluations.items():
                cd_index = int(req_number_str) - 1
                if cd_index < len(data_context.conjectural_data):
                    human_eval = Evaluation.model_validate(evaluation)
                    human_eval.compute_overall_score()
                    data_context.conjectural_data[cd_index].conjectural_requirements[-1].human_evaluation = human_eval

            state["data_context"] = data_context.model_dump()
            await copilotkit_emit_state(config, state)

            for req_number_str, evaluation in evaluations.items():
                human_eval = Evaluation.model_validate(evaluation)
                logger.debug("Requirement #%s:", req_number_str, extra={"node": "validation"})
                for criterion, score in human_eval.scores.items():
                    justification = human_eval.justifications.get(criterion, "")
                    justification_info = f' — "{justification}"' if justification else ""
                    logger.debug("  %s: %s/5%s", criterion, score, justification_info, extra={"node": "validation"})
        except Exception as e:
            logger.error("Error parsing human evaluation response", extra={"node": "validation"}, exc_info=True)
            logger.debug("Raw response: %s", human_evaluation_response, extra={"node": "validation"})

    elif not require_evaluation:
        logger.info("Human evaluation not required — skipping interrupt", extra={"node": "validation"})
    else:
        logger.info("Resuming after interrupt — human evaluation already completed", extra={"node": "validation"})

    # --- Step 2: LLM-as-Judge evaluation ---
    model_judge_provider = context.get("model_judge", "gemini")
    logger.info("Starting LLM-as-Judge evaluation (provider: %s) for %s requirements", model_judge_provider, len(data_context.conjectural_data), extra={"node": "validation"})
    judge_model_name = DEFAULT_GEMINI_MODEL if model_judge_provider == "gemini" else DEFAULT_AZURE_OPENAI_JUDGE_MODEL
    model = get_model(provider=model_judge_provider, model=judge_model_name)
    for i, cd in enumerate(data_context.conjectural_data):
        req_num = i + 1

        if not cd.conjectural_requirements:
            logger.info("Skipping #%s — no conjectural requirements", req_num, extra={"node": "validation"})
            continue

        cr = cd.conjectural_requirements[-1]
        logger.info("LLM evaluating requirement #%s (attempt %s)", req_num, cr.attempt, extra={"node": "validation"})

        prompt = get_prompt(VALIDATION_SYSTEM_PROMPT, data_context.language).format(
            project_summary=data_context.project_summary,
            domain=data_context.domain,
            stakeholder=data_context.stakeholder,
            requirement_number=req_num,
            desired_behavior=cr.ferc.desired_behavior,
            business_need=cr.ferc.business_need,
            uncertainties=cr.ferc.uncertainty,
            solution_assumption=cr.qess.solution_assumption,
            uncertainty_evaluated=cr.qess.uncertainty_evaluated,
            observation_analysis=cr.qess.observation_analysis,
            language=data_context.language,
        )

        try:
            response = await model.ainvoke([HumanMessage(content=prompt)])
            raw_content = extract_text(response.content)
            eval_result = json.loads(raw_content)
            llm_eval = Evaluation.model_validate(eval_result)
            llm_eval.compute_overall_score()
            cr.llm_evaluation = llm_eval
            logger.info("Requirement #%s evaluated (overall: %s/5)", req_num, llm_eval.overall_score, extra={"node": "validation"})
            for criterion, score in llm_eval.scores.items():
                justification = llm_eval.justifications.get(criterion, "")
                justification_info = f' — "{justification}"' if justification else ""
                logger.debug("  %s: %s/5%s", criterion, score, justification_info, extra={"node": "validation"})
        except Exception as e:
            logger.error("Error evaluating requirement #%s", req_num, extra={"node": "validation"}, exc_info=True)
            cr.llm_evaluation = Evaluation()

        state["data_context"] = data_context.model_dump()
        await copilotkit_emit_state(config, state)

    spec_attempts = context.get("spec_attempts", 3)
    if state.get("spec_attempt", 0) >= spec_attempts:
        data_context.rank_conjectural_requirements()

        saved_ids = await persist_conjectural_data(context["current_project_id"], data_context, context.get("current_user_id"))

        msg_created_text = "📑 The following **conjectural requirements** were successfully created: " + ", ".join(saved_ids) + "."
        response = AIMessage(content=msg_created_text)
        messages = messages + [response]
        await copilotkit_emit_message(config, msg_created_text)

        msg_graphic_text = "📊 Below is an example of a **chart** for the first requirement generated. For more details on other requirements, go to the reports page."
        response = AIMessage(content=msg_graphic_text)
        messages = messages + [response]
        await copilotkit_emit_message(config, msg_graphic_text)

        best_requirement_ids = []
        for entry in data_context.conjectural_data:
            for cr in entry.conjectural_requirements:
                if cr.ranking == 1 and cr.db_id:
                    best_requirement_ids.append(cr.db_id)

        # existe limitação do modelo llama-70B: suporta mais de uma tool call no context
        model_with_tools = get_model(
            provider="gpt_azure" if context["model"] == "llama_azure" else context["model"],
            temperature=0.1,
        )
        model_with_tools = model_with_tools.bind_tools([*state.get("tools", [])])

        tool_response = await model_with_tools.ainvoke(
            [
                HumanMessage(content=f"You ONLY should CALL show_requirements tool with requirement_ids: {json.dumps(best_requirement_ids)}"),
            ],
            config,
        )

        messages = messages + [tool_response]

        return {
            "messages": messages,
            "data_context": data_context.model_dump(),
            "coordinator_phase": "done",
        }
    else:
        return {
            "messages": messages,
            "data_context": data_context.model_dump(),
            "coordinator_phase": "specification",
        }


# Task registry: maps task names to handler functions
VALIDATION_TASKS = {
    "evaluate": _task_evaluate,
}


async def validation_node(state: WorkflowState, config: Optional[RunnableConfig] = None):
    """
    Validation node with task dispatch.

    Default task (first entry): evaluate conjectural requirements.
    """
    logger.info("Validation node started", extra={"node": "validation"})
    config = copilotkit_customize_config(config, emit_messages=False)

    context = extract_copilotkit_context(state)
    model_provider = context['model']
    data_context = DataContext.model_validate(state.get("data_context", {}))

    raw_task = state.get("node_task") or ""
    task_name = raw_task.split(":", 1)[1] if raw_task.startswith("validation:") else None

    if task_name and task_name in VALIDATION_TASKS:
        handler = VALIDATION_TASKS[task_name]
        logger.info("Dispatching task: %s", task_name, extra={"node": "validation"})
    else:
        handler = VALIDATION_TASKS["evaluate"]
        logger.info("Running default task: evaluate", extra={"node": "validation"})

    update = await handler(state, config, data_context, model_provider)
    if "messages" not in update:
        update["messages"] = state.get("messages", [])
    return Command(update=update)
