name: Build and Push

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: azure-container

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no ACR
        uses: azure/docker-login@v1
        with:
          login-server: acrconreq.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build e push API
        run: |
          docker build -t acrconreq.azurecr.io/api:latest -f docker/Dockerfile.api .
          docker push acrconreq.azurecr.io/api:latest

      - name: Build e push WEB
        run: |
          echo "API URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}"
          echo "API URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}"
          echo "API URL: ${{ vars.NEXT_PUBLIC_API_URL }}"
          echo "API URL: ${{ vars.LANGGRAPH_DEPLOYMENT_URL }}"
          docker build -t acrconreq.azurecr.io/web:latest -f docker/Dockerfile.web \
          --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} \
          --build-arg LANGSMITH_API_KEY=${{ secrets.LANGSMITH_API_KEY }} \
          --build-arg NEXT_PUBLIC_SUPABASE_URL=${{ vars.NEXT_PUBLIC_SUPABASE_URL }} \
          --build-arg NEXT_PUBLIC_SITE_URL=${{ vars.NEXT_PUBLIC_SITE_URL }} \
          --build-arg NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }} \
          --build-arg LANGGRAPH_DEPLOYMENT_URL=${{ vars.LANGGRAPH_DEPLOYMENT_URL }} \
          .
          docker push acrconreq.azurecr.io/web:latest

      - name: Build e push AGENT
        run: |
          docker build -t acrconreq.azurecr.io/agent:latest -f docker/Dockerfile.agent .
          docker push acrconreq.azurecr.io/agent:latest
